version: '3.0'

services:
  mysql-db:
    image: mysql:latest
    networks:
      - back-end
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure



  api:
    image: api-filmes/api-filmes:1.0.0
    networks:
     - back-end
    ports: 
      - "5039:5039"
    build:
      context: . 
      dockerfile: Dockerfile
    depends_on: 
      - mysql-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
   
     


volumes:
  mysql-data:

networks:
  back-end:


