apiVersion: v2
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
     app: mysql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "${MYSQL_ROOT_PASSWORD}"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "${MYSQL_RANDOM_ROOT_PASSWORD}"
      volumes:
        - name: mysql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5039
      targetPort: 5039
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api-filmes/api-filmes:1.0.0
          ports:
            - containerPort: 5039
          env:
            - name: MYSQL_DATABASE
              value: "${MYSQL_DATABASE}"
            - name: MYSQL_USER
              value: "${MYSQL_USER}"
            - name: MYSQL_ROOT_PASSWORD
              value: "${MYSQL_ROOT_PASSWORD}"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          dependsOn:
            - api
      volumes:
        - name: mysql-data
          emptyDir: {}
